name: jp_optical
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.1
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.10+1
  outlined_text: ^1.0.1
  shimmer: ^3.0.0
  http: ^1.2.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  responsive_grid_list: ^1.4.0
  flick_video_player: ^0.8.0
  cloud_firestore: ^5.0.2
  rxdart: ^0.28.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.5
  provider: ^6.0.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

