// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2V0Qiiwzm6niyUD5MxnjbCtN9h9sd5q8',
    appId: '1:796975223546:web:b9c1e57dd55d82a796af43',
    messagingSenderId: '796975223546',
    projectId: 'rj-brothers-e9d57',
    authDomain: 'rj-brothers-e9d57.firebaseapp.com',
    storageBucket: 'rj-brothers-e9d57.appspot.com',
    measurementId: 'G-1HEWHMT4VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIPCt5LNHgaE0bl1QJbkkGUS_1PEM1R5Q',
    appId: '1:796975223546:android:3b123eff33c0695b96af43',
    messagingSenderId: '796975223546',
    projectId: 'rj-brothers-e9d57',
    storageBucket: 'rj-brothers-e9d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2sC3uPg_kAm5GTX3zGj2oA1MNolM4PU',
    appId: '1:796975223546:ios:56c3093ba1b4e51a96af43',
    messagingSenderId: '796975223546',
    projectId: 'rj-brothers-e9d57',
    storageBucket: 'rj-brothers-e9d57.appspot.com',
    iosBundleId: 'com.example.jpOptical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2sC3uPg_kAm5GTX3zGj2oA1MNolM4PU',
    appId: '1:796975223546:ios:56c3093ba1b4e51a96af43',
    messagingSenderId: '796975223546',
    projectId: 'rj-brothers-e9d57',
    storageBucket: 'rj-brothers-e9d57.appspot.com',
    iosBundleId: 'com.example.jpOptical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2V0Qiiwzm6niyUD5MxnjbCtN9h9sd5q8',
    appId: '1:796975223546:web:20d4ccea6a21157196af43',
    messagingSenderId: '796975223546',
    projectId: 'rj-brothers-e9d57',
    authDomain: 'rj-brothers-e9d57.firebaseapp.com',
    storageBucket: 'rj-brothers-e9d57.appspot.com',
    measurementId: 'G-HVCKDVZRVN',
  );
}
